ajout de photo Léo Boizard
eemi-aj/trombi pull request #114
Opened 2019-03-15 11:24 UTC by lobzd

Bonjour Adrien,

Pouvez-vous intégrer mes modifications au trombi de la classe ? 

Bonne journée

Léo Boizard

2019-03-16 17:22 UTC, adrienjoly requested changes
Merci pour cette PR !

Critères d'évaluation:

- shipped: 1 point si PR soumise à temps + 1 point si URL fournie sur classroom ✅
- clean commit: 2 points pour clarté des messages de commit ✅✅
- good desc: 1 point pour formulation de l'objectif de PR dans la description + 1 point pour courtoisie et bonne orthographe ✅✅
- git howto: 2 points pour mise en oeuvre est expliquée clairement et précisément en description de PR.
- valid code: 2 points pour code HTML 100% valide et sans erreur (aucun code HTML livré !)
- concise code: 2 points si PR n'ajoute que le code nécéssaire sans impacter le reste du code.
- clean code: 2 points pour code bien intenté et lisible.
- pro content: 2 points si la fiche étudiant(e) est écrite de manière professionelle, sans fautes d'orthographes.
- image: 1 point pour présence de photo dans PR + 1 point si bien retaillée aux dimensions 128x128 pixels ✅✅
- img naming: 2 points pour respect convention de nommage de la photo + référence correcte du fichier dans le code html ✅

=> 8 / 20

Il manque la partie HTML dans ta PR !

Merci la corriger pour que je puisse la fusionner.

2019-03-18 12:16 UTC, lobzd commented
Bonjour Adrien,

J'ai effectué la modification du fichier html comme convenu en utilisant les commandes suivantes : 
git add classe-fast-track.html
git commit -m "ajout de ma ligne de commande ..."
 Mon terminal ne reconnaissait pas la photo dans le dossier j'ai finalement trouvé une solution.
J'ai donc ajouté la photo dans le dossier photos du Trombi avec ces commandes
git add photos/Leo-boizard.jpg
git commit -m "Ajout de ma photo dans le dossier..."

Merci d'accepter ma nouvelle PR.

Leo Boizard

2019-03-18 18:34 UTC, adrienjoly approved these changes

2019-03-18 18:35 UTC, adrienjoly commented
+ 1 pt pour avoir ajouté le code html et la mise en oeuvre

=> note: 9 / 20

2019-03-18 19:33 UTC, merged