Modification du fichier html et ajout de la ligne victor marignac
eemi-aj/trombi pull request #123
Opened 2019-03-15 16:19 UTC by victor-marignac

Bonjour, 

Voici ma contribution au trombinoscope de la classe fast-track comprenant modification de ma ligne et ajout de ma photo,

Cordialement,
Victor MARIGNAC

2019-03-16 19:05 UTC, adrienjoly requested changes
Merci pour cette PR !

Critères d'évaluation:

- shipped: 1 point si PR soumise à temps + 1 point si URL fournie sur classroom ✅
- clean commit: 2 points pour clarté des messages de commit ✅✅
- good desc: 1 point pour formulation de l'objectif de PR dans la description + 1 point pour courtoisie et bonne orthographe ✅✅
- git howto: 2 points pour mise en oeuvre est expliquée clairement et précisément en description de PR. => aucune 
- valid code: 2 points pour code HTML 100% valide et sans erreur ✅✅
- concise code: 2 points si PR n'ajoute que le code nécéssaire sans  impacter le reste du code. ✅✅
- clean code: 2 points pour code bien intenté et lisible. ✅✅
- pro content: 2 points si la fiche étudiant(e) est écrite de manière professionelle, sans fautes d'orthographes. ✅✅
- image: 1 point pour présence de photo dans PR + 1 point si bien retaillée aux dimensions 128x128 pixels => photo non incluse
- img naming: 2 points pour respect convention de nommage de la photo + référence correcte du fichier dans le code html ✅

=> 14 / 20

Merci de compléter la PR en vue de sa fusion.

2019-03-17 11:45 UTC, victor-marignac commented
Bonjour, 

Apparemment j'avais oublié d'add ma photo lors de ma précédente PR, chose faite à présent, elle est redimensionnée en 128x128, je vous joint l'url par Classroom,

Bien à vous,
Victor Marignac

2019-03-17 15:41 UTC, victor-marignac commented
Bonjour,

Je viens de me rendre compte que je n’avais également pas commenté la manière dont je me suis pris pour modifier les documents.

1) Pour commencer je suis allé grâce à la commande cd dans le dossier outils 2 créé la dernière fois un cours.
2) une fois dans le dossier j’ai git clone le lien obtenu sur git hub.
3) puis j’ai utilisé VIM pour modifier le fichier html en rajoutant ma ligne et modifiant les informations nécessaires
4) ensuite je suis remonté jusqu’à mon dossier photo personnel contenant ma photo redimensionnée en 128x128 avec la commande suivante :
cd / puis cd mnt/c/Users/vmari/Pictures
5) une fois dans mon dossier photo j’ai copié ma photo avec la commande cp et je suis remonté jusqu’au fichier git avec la commande suivante:
cp photo ~/outils2/trombi/photos puis entrer.
6) une fois la photo transférée et le document html modifié j’ai git add les deux documents puis commit -m puis push.

2019-03-18 18:24 UTC, adrienjoly approved these changes

2019-03-18 18:25 UTC, adrienjoly commented
+1.5 pts pour avoir ajouté la photo, complété la mise en oeuvre et ajouté l'URL sur classroom

=> note: 15,5 / 20

2019-03-18 19:42 UTC, merged