demande ajout bio+photo tristan saudubray
eemi-aj/trombi pull request #15
Opened 2018-11-08 14:55 UTC by TricriX

bonjour
Voici les modification à ajouter contenant photo et bio 
bien cordialement 
Tristan Saudubray

2018-11-11 13:59 UTC, adrienjoly requested changes
Merci pour ta proposition, Tristan !

Preview: https://rawcdn.githack.com/eemi-aj/trombi/d6e5fe034d4bbdf1d2eb0f2267a8a1e74ef99d35/classe1.html

Peux-tu retailler ta photo afin qu'elle fasse 128 x 128 pixels comme demandé, stp ?

2018-11-11 14:04 UTC, TricriX commented
J ai essayé mais comme elle est naturellement rectangulaire lorsque je change la taille de la largeur la hauteur se met automatiquement et je n’arrive pas conséquent pas à la rendre carré  

Provenance : Courrier pour Windows 10

De : Adrien Joly
Envoyé le :dimanche 11 novembre 2018 14:59
À : eemi-aj/trombi
Cc : TricriX; Author
Objet :Re: [eemi-aj/trombi] Tristan Saudubray - Classe 1 (#15)

@adrienjoly requested changes on this pull request.
Merci pour ta proposition, Tristan !
Preview: https://rawcdn.githack.com/eemi-aj/trombi/d6e5fe034d4bbdf1d2eb0f2267a8a1e74ef99d35/classe1.html
Peux-tu retailler ta photo afin qu'elle fasse 128 x 128 pixels comme demandé, stp ?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


-- 
*Ce message électronique provient de l'adresse e-mail d'un étudiant de 
l'EEMI. Les idées et opinions présentées dans ce message sont celles de son 
auteur et ne représentent pas nécessairement celles de l'EEMI.*

2018-11-11 14:32 UTC, adrienjoly commented
Je t'invite à demander de l'aide à tes camarades (ou à Google), pour apprendre à retailler une image rectangulaire au format carré. Tu peux utiliser le canal "dev-entraide" du tchat Mattermost de l'EEMI pour demander de l'aide à tes camarades.

2018-11-19 10:59 UTC, adrienjoly submitted a review, later dismissed
LGTM

2018-11-19 11:00 UTC, merged